In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,f1_score,class_likelihood_ratios
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('insurance.csv')

In [3]:
df.sample(5)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
31,39,51.1,1.83,11.77,True,Lucknow,private_job,Medium
39,51,100.6,1.68,11.99,True,Bangalore,unemployed,High
20,34,58.2,1.85,30.65,True,Gaya,business_owner,Medium
80,56,95.8,1.67,50.00,False,Jalandhar,unemployed,High
81,41,82.6,1.61,22.19,True,Mysore,freelancer,High

In [4]:
df_feat = df.copy()

In [5]:
df_feat.sample(5)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
11,25,77.2,1.56,10.899387,True,Pune,government_job,Low
61,32,102.4,1.68,24.050000,True,Chandigarh,unemployed,High
40,44,57.0,1.53,40.190000,True,Pune,unemployed,Medium
14,49,89.3,1.65,13.505166,False,Kota,government_job,Medium
86,35,66.0,1.89,37.380000,False,Hyderabad,freelancer,Low

In [6]:
#1. Feature in Bmi 
df_feat['bmi'] = df_feat['weight']/(df_feat["height"]**2)

In [7]:
df_feat.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi
0,67,119.8,1.56,2.92,False,Jaipur,retired,High,49.227482
1,36,101.1,1.83,34.28,False,Chennai,freelancer,Low,30.189017
2,39,56.8,1.64,36.64,False,Indore,freelancer,Low,21.118382
3,22,109.4,1.55,3.34,True,Mumbai,student,Medium,45.535900
4,69,62.2,1.60,3.94,True,Indore,retired,High,24.296875

In [8]:
#2. Feature 2 age group 

def age_group(age):
    if age <25 :
        return 'young'
    elif age<45:
        return 'adult'
    elif age <60:
        return 'middle_aged' 
    return 'senior'

In [9]:
df_feat['age_group'] = df_feat['age'].apply(age_group)

In [15]:
df_feat.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi,age_group,city_tire
0,67,119.8,1.56,2.92,False,Jaipur,retired,High,49.227482,senior,2
1,36,101.1,1.83,34.28,False,Chennai,freelancer,Low,30.189017,adult,1
2,39,56.8,1.64,36.64,False,Indore,freelancer,Low,21.118382,adult,2
3,22,109.4,1.55,3.34,True,Mumbai,student,Medium,45.535900,young,1
4,69,62.2,1.60,3.94,True,Indore,retired,High,24.296875,senior,2

In [11]:

tier_1_cities = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"]
tier_2_cities = [
    "Jaipur", "Chandigarh", "Indore", "Lucknow", "Patna", "Ranchi", "Visakhapatnam", "Coimbatore",
    "Bhopal", "Nagpur", "Vadodara", "Surat", "Rajkot", "Jodhpur", "Raipur", "Amritsar", "Varanasi",
    "Agra", "Dehradun", "Mysore", "Jabalpur", "Guwahati", "Thiruvananthapuram", "Ludhiana", "Nashik",
    "Allahabad", "Udaipur", "Aurangabad", "Hubli", "Belgaum", "Salem", "Vijayawada", "Tiruchirappalli",
    "Bhavnagar", "Gwalior", "Dhanbad", "Bareilly", "Aligarh", "Gaya", "Kozhikode", "Warangal",
    "Kolhapur", "Bilaspur", "Jalandhar", "Noida", "Guntur", "Asansol", "Siliguri"
]

In [13]:
# Filter 
def city_tire(city):
    if city in tier_1_cities:
        return 1
    elif city in tier_2_cities:
        return 2
    else:
        return 2

In [14]:
df_feat['city_tire'] = df_feat["city"].apply(city_tire)

In [ ]:
# Feature 4 
def lifestyle_risk(row):
    if row["smoker"] and row["bmi"] > 30:
        return "high"
    elif row["smoker"] or row["bmi"] > 27:
        return "medium"
    else:
        return "low"

In [22]:
df_feat["lifestyle_risk"] = df_feat.apply(lifestyle_risk, axis=1)

In [23]:
df_feat.sample(5)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi,age_group,city_tire,lifestyle_risk
87,30,82.0,1.60,25.59837,False,Hyderabad,government_job,Low,32.031250,adult,1,medium
0,67,119.8,1.56,2.92000,False,Jaipur,retired,High,49.227482,senior,2,medium
46,42,83.0,1.57,25.57000,True,Kolkata,unemployed,High,33.672766,adult,1,high
60,41,101.3,1.81,49.94000,True,Jalandhar,unemployed,High,30.920912,adult,2,high
21,69,92.7,1.84,2.91000,False,Jalandhar,retired,High,27.380671,senior,2,medium